import "@/styles/styles.scss";
import type {Metadata} from "next";
import Sphere from "@/components/sphere";
import {Suspense} from "react";
import YandexMetrica from "@/components/yandex-metrika";

export const metadata: Metadata = {
  title: "Портфолио",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
    <body>
    <main>
      <Suspense fallback={null}>
        {children}
        <YandexMetrica />
      </Suspense>
      <Sphere/>
    </main>
    </body>
    </html>
  );
}
