import "@/styles/styles.scss";
import type {Metadata} from "next";
import Sphere from "@/components/sphere";

export const metadata: Metadata = {
  title: "Портфолио",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
    <body>
    <main>
      {children}
      <Sphere/>
    </main>
    </body>
    </html>
  );
}
